# WEP WPA supported, other support may vary
CIRCUITPY_WIFI_SSID="free4all_2G"
CIRCUITPY_WIFI_TYPE="WPA"
CIRCUITPY_WIFI_PASSWORD="password"
CIRCUITPY_WEB_API_PORT=80
CIRCUITPY_WEB_API_PASSWORD="password"
test_variable="this is a test"
thumbs_up="\U0001f44d"
CIRCUITPY_HEAP_START_SIZE=2048000
CIRCUITPY_PYSTACK_SIZE=8000